# This namespace allows you to define where the services are installed into.
# If not set then they use the namespace of the release.
# This is helpful when installing cert manager as a chart dependency (sub chart).
namespace: cert-manager

# This option is equivalent to setting crds.enabled=true and crds.keep=true.
installCRDs: true
